// ─── DESIGN TOKENS ───────────────────────────────────────────────────────────
export const C = {
  primary: '#003B95',
  secondary: '#0071C2',
  accent: '#FFB700',
  bg: '#F5F5F5',
  card: '#FFFFFF',
  text: '#333333',
  textLight: '#6B7280',
  border: '#E5E7EB',
  success: '#00875A',
  danger: '#D32F2F',
  gradient: 'linear-gradient(135deg, #003B95 0%, #0071C2 100%)',
};

export const BTN = {
  primary: {
    background: C.gradient,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '10px 22px',
    fontWeight: 700,
    cursor: 'pointer',
    fontSize: 14,
    letterSpacing: 0.3,
  },
  accent: {
    background: C.accent,
    color: C.text,
    border: 'none',
    borderRadius: 8,
    padding: '10px 22px',
    fontWeight: 700,
    cursor: 'pointer',
    fontSize: 14,
  },
  outline: {
    background: 'transparent',
    color: C.primary,
    border: `2px solid ${C.primary}`,
    borderRadius: 8,
    padding: '9px 20px',
    fontWeight: 700,
    cursor: 'pointer',
    fontSize: 14,
  },
  ghost: {
    background: 'transparent',
    color: C.textLight,
    border: 'none',
    borderRadius: 6,
    padding: '8px 16px',
    cursor: 'pointer',
    fontSize: 14,
  },
  danger: {
    background: C.danger,
    color: '#fff',
    border: 'none',
    borderRadius: 8,
    padding: '9px 18px',
    fontWeight: 700,
    cursor: 'pointer',
    fontSize: 13,
  },
};
